### Site metadata

title: Artist's Portfolio
description: A gallery of images for an artist's portfolio, built with Jekyll

url: "https://artists-portfolio.netlify.app"
baseurl: ""

github_username: "knowndisc"
repository: "knowndisc1/knowndisc"

google_analytics_key: ""

# For SEO tag.
logo: /siteicon.png
author:
  name: knowndisc
  twitter: knowndisc2
social:
  name: My Art
  links:

### Build settings

timezone: Etc/UTC

permalink: pretty

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      text_width: true
  - scope:
      path: "index.html"
    values:
      text_width: false

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - README.md
  - LICENSE
  - LICENCE-source
  - Makefile
  - netlify.toml
